name: Build and Deploy BirthdayBuddyLeftChatBot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: TelegramBotRunners
    environment: production

    steps:
      # 🔁 Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4
        # → После этого все файлы есть в рабочей директории (Runner создаёт временную рабочую папку /home/runner/_work/BirthdayBuddyLeftChat/BirthdayBuddyLeftChat)

      # ⚙️ Шаг 2: Устанавливаем .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 🛠️ Шаг 3: Восстанавливаем зависимости
      - name: Restore dependencies
        run: dotnet restore

      # 🛠️ Шаг 4: Собираем и публикуем
      - name: Build and Publish
        run: |
          dotnet publish \
          --configuration Release \
          --output ./publish \
          --nologo \
          --verbosity minimalse

      # 📁 Шаг 5: Копируем Settings.json (если не скопировался автоматически)
      - name: Копирование настроек
        run: cp Settings.json ./publish/ || echo "Warning: Settings.json не найден!"

      # 🚀 Шаг 6: Деплой на целевой сервер
      - name: Отправка на сервер
        run: |
          
          # Отправляем на сервер
          # scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./publish/* root@telegram.local:/root/publish/BirthdayBuddyLeftChat/

      # 🔁 Шаг 7 Перезапуск сервиса
      - name: Перезапуск сервиса
        run: systemctl restart BirthdayBuddyLeftChat.service

      # 🚀 Шаг 8 Проверка статуса сервиса
      - name: Проверка статуса сервиса
        run: systemctl status BirthdayBuddyLeftChat.service --no-pager